#pragma once

#define VERSION_LUNA_MAJOR 3
#define VERSION_LUNA_MINOR 7
#define VERSION_LUNA_PATCH 3

#define VERSION_LUNA_HOTFIX "a"

#define VERSION_LUNA_STR_HELPER(x) #x
#define VERSION_LUNA_STR(x) VERSION_LUNA_STR_HELPER(x)

#define VERSION_LUNA VERSION_LUNA_STR(VERSION_LUNA_MAJOR) "." VERSION_LUNA_STR(VERSION_LUNA_MINOR) "." VERSION_LUNA_STR(VERSION_LUNA_PATCH)
